version: '3'

services:
  raspberry-service:
    build: ./raspberry
    ports:
      - "2222:2222"
      - "8000:8000"


  esp32:
    build: ./esp32
    ports:
      - "5555:5555"
      - "3333:3333"
      - "1234:1234"
    depends_on:
      - raspberry-service
