---

- name: Setup raspberry pi
  hosts: pi
  tasks:
    - name: Wait 150 seconds for raspberry pi to boot, but only start checking after 10 seconds
      wait_for_connection:
        delay: 10
        timeout: 150

    - name: Install python3-pip, gunicorn3 and lsof
      apt:
        name:
          - python3-pip
          - gunicorn3
          - lsof
        update_cache: yes
        autoclean: yes
        state: present
      become: True
        
    - name: Pip3 install falcon
      pip: 
        name: falcon
        executable: /usr/bin/pip3
      become: True

    - name: Kill previous process running on port 8000, if exists
      become: yes
      shell: "pkill -9 $(lsof -t -i:8000)"
      ignore_errors: yes

    - name: Copy server.py into remote
      copy:
        src: ./server.py
        dest: /home/pi

    - name: Start server with gunicorn3
      shell: "cd /home/pi; nohup gunicorn3 -b 0.0.0.0:8000 server:app </dev/null >/dev/null 2>&1 &"
