---

- name: Setup raspberry pi
  hosts: pi
  tasks:
    - name: Wait 200 seconds for raspberry pi to boot, but only start checking after 30 seconds
      wait_for_connection:
        delay: 30
        timeout: 300
        
    - name: Install mosquitto
      become: yes
      apt:
        name: mosquitto
